{
    "version": 1584907378,
    "fileList": [
        "data.js",
        "c2runtime.js",
        "jquery-3.4.1.min.js",
        "offlineClient.js",
        "images/background.png",
        "images/bottomtile.png",
        "images/bottom_tile_bar-sheet0.png",
        "images/player-sheet0.png",
        "images/player-sheet1.png",
        "images/player-sheet2.png",
        "images/enemies-sheet0.png",
        "images/blackscreen-sheet0.png",
        "images/board_gameover-sheet0.png",
        "images/score_board-sheet0.png",
        "images/play_btn-sheet0.png",
        "images/menu_btn-sheet0.png",
        "images/ghost2-sheet0.png",
        "images/ghost2-sheet1.png",
        "images/title-sheet0.png",
        "images/next-sheet0.png",
        "images/next-sheet1.png",
        "images/particles.png",
        "images/particles2.png",
        "images/title2-sheet0.png",
        "images/sound-sheet0.png",
        "images/spritefont.png",
        "images/marca_d_agua-sheet0.png",
        "images/new_logofw-sheet0.png",
        "media/correct.m4a",
        "media/correct.ogg",
        "media/play.ogg",
        "media/pop.ogg",
        "media/selection.m4a",
        "media/selection.ogg",
        "media/game-die2.ogg",
        "media/lobby time.m4a",
        "media/lobby time.ogg",
        "icon-16.png",
        "icon-32.png",
        "icon-114.png",
        "icon-128.png",
        "icon-256.png",
        "loading-logo.png"
    ]
}