var TEXT_HELP1 = "DESTROY THE BLOCKS TO MOVE YOUR HEXAGON DOWN";
var TEXT_HELP2 = "TRY NOT TO FALL OUT OF THE TOWER OR YOU'LL LOSE";
var TEXT_HELP3 = "AND REMEMBER: USE THE SPECIAL SQUARES CAREFULLY!";

var TEXT_BEST = "BEST";
var TEXT_BEST_SCORE = "YOUR BEST SCORE";
var TEXT_SCORE = "SCORE";
var TEXT_GAMEOVER = "GAME OVER!\nTRY AGAIN?";
var TEXT_ARE_SURE = "ARE YOU SURE YOU WANT TO EXIT? ALL UNSAVED PROGRESS WILL BE LOST";
var TEXT_NEWBESTSCORE = "NEW BEST SCORE!";

var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_CREDITS_DEVELOPED = "BROUGHT TO YOU BY";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";