var CANVAS_WIDTH = 768;
var CANVAS_HEIGHT = 1400;
var CANVAS_WIDTH_HALF = 768 * 0.5;
var CANVAS_HEIGHT_HALF = 1400 * 0.5;

var EDGEBOARD_X = 0;
var EDGEBOARD_Y = 100;

var FPS = 30;
var FPS_TIME = 1000 / FPS;
var DISABLE_SOUND_MOBILE = false;

var PRIMARY_FONT = "comfortaa";
var PRIMARY_FONT_COLOUR = "#ffffff";
var SECONDARY_FONT_COLOUR = "#000000";

var MULTIPLIER_DIVIDER = 20;
var BLOCK_HALF_SIZE = 50;
var EXPLOSION_SIZE = 300;
var SCORE_DIFFICULTY_LIMIT = 2000;
var MENU_TIMER_LIMIT = 3000;
var MENU_BLOCKS_ROTATION = 3;
var MENU_BLOCKS_SPEED = 5;
var BACKGROUND_MOVEMENT_VAR = 10;

// BOX 2D SETTINGS
var TIMESTEP = 1 / 60;
var VELOCITY_ITERATIONS = 10;
var POSITION_ITERATIONS = 10;
var UPDATE_LOOP_VAR = 3;
var DEBUG_BOX2D = false;
var DEBUG_BOX2D_ALPHA = 0.5;
var WORLD_SCALE = 100;
var GRAVITY = 9.81;
var FLOOR_VELOCITY_MULTIPLIER = 0.1;
var FLOOR_LERP_DIVIDER = 4;
var BLOCKS_PADDING_X = 0.1;
var BLOCKS_PADDING_Y = 0.2;
var BLOCK_DENSITY = 1;
var PLAYER_DENSITY = 1;
var FLOOR_DENSITY = 1;
var BLOCK_FRICTION = 1;
var FLOOR_FRICTION = 1;
var PLAYER_FRICTION = 1;
var BLOCK_RESTITUTION = 0.01;
var FLOOR_RESTITUTION = 0.01;
var PLAYER_RESTITUTION = 0.01;
var FLOOR_COVER_Y = CANVAS_HEIGHT - 150;
var FLOOR_Y_START = CANVAS_HEIGHT + 450; // WHERE THE FLOOR WILL BE CREATED (Y POS)
var FLOOR_Y_LIMIT = FLOOR_Y_START - 600; // WHEN THE FLOOR WILL ARRIVE AT THIS Y POS, A NEW MATRIX WILL BE CREATED
var MATRIX_X_START = CANVAS_WIDTH_HALF - (2 * BLOCK_HALF_SIZE);
var MATRIX_Y_START = FLOOR_Y_LIMIT + 100; // WHERE THE MATRIX WILL BE CREATED (Y POS)
var PLAYER_OFFSCREEN_TOLERANCE = 150;
var PLAYER_START_X = CANVAS_WIDTH_HALF;
var PLAYER_START_Y = CANVAS_HEIGHT_HALF - 200;
var PLAYER_Y_LIMIT = CANVAS_HEIGHT_HALF;
var BLOCK_FALLING_SPEED_LIMIT = 10;
var BLOCK_SPEED_LIMIT = 8;
var FLOOR_LIMIT_SCALED = FLOOR_Y_LIMIT / WORLD_SCALE;
var FLOOR_Y_START_SCALED = FLOOR_Y_START / WORLD_SCALE;
var PLAYER_LIMIT_SCALED = PLAYER_Y_LIMIT / WORLD_SCALE;
var BLOCK_HALF_SIZE_SCALED = BLOCK_HALF_SIZE / WORLD_SCALE;

// BOX 2D OBJECT CREATIONS
var PLAYER = "Player";
var BLOCK_0 = 0;
var BLOCK_1 = 1;
var BLOCK_2 = 2;
var BLOCK_3 = 3;
var BLOCK_4 = 4;
var BLOCK_5 = 5;
var BLOCK_6 = 6;
var BLOCK_7 = 7;
var BLOCK_8 = 8;
var BLOCK_9 = 9;
var BLOCK_10 = 10;
var BLOCK_11 = 11;
var BLOCK_12 = 12;
var BLOCK_13 = 13;
var BLOCK_14 = 14;
var BLOCK_SPEED = 97;
var BLOCK_BOMB = 98;
var BLOCK_BONUS = 99;

// BOX 2D BODY SETTINGS
var DYNAMIC_BODY = 0;
var STATIC_BODY = 1;
var CONTACT_BEGIN = 0;
var CONTACT_END = 1;
var CONTACT_PRESOLVE = 2;
var CONTACT_POSTSOLVE = 3;

var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;

var MATRIX_SPEED;
var BLOCK_VALUE;
var BLOCK_BONUS_VALUE;

var STATE_LOADING = 0;
var STATE_MENU = 1;
var STATE_HELP = 2;
var STATE_GAME = 3;
var ON_MOUSE_DOWN = 0;
var ON_MOUSE_UP = 1;
var ON_MOUSE_OVER = 2;
var ON_MOUSE_OUT = 3;

var SOUNDTRACK_VOLUME_IN_GAME = 0.5;