TEXT_GAMEOVER = "GAME OVER";
TEXT_SCORE = "SCORE";
TEXT_PLAY = "PLAY";
TEXT_RESTART = "RESTART";
TEXT_TIME = "TIME";
TEXT_SCORE = "SCORE";
TEXT_LEVELEND = "LEVEL ";
TEXT_COMPLETEEND = " COMPLETE";

TEXT_SPLAT = "SPLAT!";
TEXT_DROWN = "GLU GLU..";
TEXT_CRASH = "BONK!";
TEXT_GREAT = "GREAT!!";

TEXT_HELP1 = "USE ARROWS KEYS TO REACH THE OTHER SIDE OF THE RIVER BEFORE TIME RUNS OUT. TO COMPLETE A LEVEL, YOU HAVE TO PUT A FROG ON EACH OF THE 5 COVES";
TEXT_HELP2 = "DON’T GET DRIVEN OVER BY CARS ALONG THE STREET";
TEXT_HELP3 = "USE THE FLOATING TRUNKS OR TURTLE SHELLS TO CROSS THE RIVER";
TEXT_HELP4 = "IF YOU CATCH A FLY, YOU GET EXTRA POINTS";

TEXT_HELP_MOB1 = "SWIPE TO REACH THE OTHER SIDE OF THE RIVER BEFORE TIME RUNS OUT. TO COMPLETE A LEVEL, YOU HAVE TO PUT A FROG ON EACH OF THE 5 COVES";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better";